# Run me by typing `mythx analyze` in the directory of the yml file! :)

ci: true
confirm: true
analyze:
    mode: quick
    async: true
    create-group: true
    solc: 0.6.12
    remappings:
        - "@openzeppelin=node_modules/@openzeppelin"
    targets:
        - contracts/TulipMaker.sol:TulipMaker
        - contracts/TulipToken.sol:TulipToken
        - contracts/TulipGarden.sol:TulipGarden
        - contracts/MasterGardener.sol:MasterGardener
        - contracts/governance/Timelock.sol:Timelock
